### ISSUE TITLE
Send 500 status code when error connecting to host

### ISSUE THREAD

**Issue by wtip** [rverchere/vmware_exporter#11]
When the exporter is not able to connect to a host it logs a `Error, cannot connect to vmware` message but returns a blank http metrics page. This causes prometheus to think the target is still up.

It would be better if the exporter returned a 500 status code.

Here's an example https://github.com/prometheus/snmp_exporter/blob/30cb5cc264d1a3c2329ed40e740f57f3670fe1ee/snmp_exporter/http.py#L52

**Comment by wtip** [comment]
#14 submitted pull request for this issue

**Comment by rverchere** [comment]
Code merged, thanks for your contribution!
