### ISSUE TITLE
exporter is refreshing vcenter datastore states every one minutes

### ISSUE THREAD

**Issue by nivshlomokaltura** [rverchere/vmware_exporter#20]
Hello,

Exporter is getting vcenter (5.5\6.0.2) to refresh datastore information as a vcenter task each query cycle and flood the task viewer.

i would suggest to remove  ds.RefreshDatastoreStorageInfo() from vmware_exporter.py

**Comment by wtip** [comment]
Might be better to close this issue and add a comment to #18

**Comment by nivshlomokaltura** [comment]
Merged with #18
