### ISSUE TITLE
vmware_vm_cpu_ready_summation is not very useful without the number of vCPUs on the VM

### ISSUE THREAD

**Issue by dannyk81** [rverchere/vmware_exporter#30]
This value is in millseconds over the observed interval, on it's own it doesn't provide much insight and usually it is translated into a percentage value using the following formula:

```
(<value> / (<interval> * 1000)) * 100 = % CPU ready
```

for example, if the value is 1000 and the interval is 20 (Real-time), the result is:
```
(1000 / (20s * 1000)) * 100 = 5% CPU ready
```

The result of above calculations are a sum of each virtual CPUs %RDY time, However, it is more accurate to calculate the % CPU Ready per vCPU, mainly because 5% on 1 vCPU VM is a problem, however 5% on an 8 vCPU VM is OK (0.625% per vCPU)

In order to get the % CPU Ready per vCPU, we need to know how many vCPU each VM has, currently the exporter doesn't collect this information.

**Comment by dannyk81** [comment]
I believe #31 takes care of this.

@rverchere for your consideration 😄

**Comment by rverchere** [comment]
Merged, thanks !
