### ISSUE TITLE
Add package files

### ISSUE THREAD

**Issue by rverchere** [rverchere/vmware_exporter#7]
Add `setup.py`, `requirements.txt` and co to make it a clean python package.

**Comment by amcintosh** [comment]
I can take this on. 
It'll need a bit of moving around of things.

**Comment by amcintosh** [comment]
I've put up a PR for this. 
I set the version to `0.1.0`, but we can make this whatever you would prefer.

**Comment by rverchere** [comment]
Hi @amcintosh, thanks for the PR. I'll review it before the end of this week.

**Comment by rverchere** [comment]
Last week was long ;)
