### ISSUE TITLE
connection to vcenter lost

### ISSUE THREAD

**Issue by is4it-lab** [rverchere/vmware_exporter#9]
Hi,

it seems that the vmware_exporter didn't make a reconnect, when the vcenter server ist rebooted or switched over by vcenter HA.

regards 
Robert

**Comment by rverchere** [comment]
Hi,

yes, for now it connects to vcenter when starting, and does not handle disconnect/reconnect.
This will be fixed with #5, as it will manage multiple connections.

**Comment by rverchere** [comment]
Fixed, as it connect/disconnect each time it collects data.
